name: CD - Update Manifest

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'New image tag from CI'
        required: true

jobs:
  update-manifest:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v5.0.0

      - name: Update image tag in deployment.yaml
        run: |
          sed -i 's|image:.*|image: hyein02/clearhouse-back:${{ github.event.inputs.image_tag }}|g' ClearHouse-back/deployment.yaml

      - name: Commit and push changes
        run: |
          git config --global user.name 'hil679'
          git config --global user.email 'hil679922@gmail.com'
          git add ClearHouse-back/deployment.yaml
          git commit -m "Update image to ${{ github.event.inputs.image_tag }}"
          git pull --rebase
          git push
